# Generated by Django 5.1.3 on 2024-11-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": [
                    "is_completed",
                    models.Case(
                        models.When(priority="CR", then=0),
                        models.When(priority="HP", then=1),
                        models.When(priority="MP", then=2),
                        models.When(priority="LP", then=3),
                        models.When(priority="BL", then=4),
                        output_field=models.IntegerField(),
                    ),
                    "deadline",
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="projecttype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={"ordering": ["position"]},
        ),
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workers",
                to="management.position",
            ),
        ),
    ]
