# Generated by Django 5.1.3 on 2024-12-22 09:40

import django.core.validators
import django.db.models.deletion
import management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial_squashed_0004_alter_project_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    management.validators.validate_no_special_characters,
                    django.core.validators.MinLengthValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.DateField(
                validators=[management.validators.validate_future_date]
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    management.validators.validate_no_special_characters,
                    django.core.validators.MinLengthValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="management.projecttype",
            ),
        ),
        migrations.AlterField(
            model_name="projecttype",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    management.validators.validate_no_special_characters,
                    django.core.validators.MinLengthValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    management.validators.validate_no_special_characters,
                    django.core.validators.MinLengthValidator(3),
                ],
            ),
        ),
    ]
